const std = @import("std");

const GeneratedTool = struct {
    name: []const u8,
    label: []const u8,
    mutates: bool,
};

const generated_tools = [_]GeneratedTool{
    .{ .name = "read", .label = "Read File", .mutates = false },
    .{ .name = "bash", .label = "Run Bash", .mutates = true },
    .{ .name = "edit", .label = "Edit File", .mutates = true },
    .{ .name = "write", .label = "Write File", .mutates = true },
};

pub fn main(init: std.process.Init) !void {
    var stdout_buffer: [4096]u8 = undefined;
    var stdout_writer = std.Io.File.stdout().writer(init.io, &stdout_buffer);
    const stdout = &stdout_writer.interface;

    try emitRust(stdout);
    try stdout.flush();
}

fn emitRust(writer: *std.Io.Writer) !void {
    try writer.writeAll("// Generated by rust/zig-codegen/tool_registry.zig. Do not edit.\n");
    try writer.writeAll("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    try writer.writeAll("pub struct GeneratedTool {\n");
    try writer.writeAll("    pub name: &'static str,\n");
    try writer.writeAll("    pub label: &'static str,\n");
    try writer.writeAll("    pub mutates: bool,\n");
    try writer.writeAll("}\n\n");

    try writer.print("pub const ZIG_GENERATED_TOOL_COUNT: usize = {};\n\n", .{generated_tools.len});

    try writer.writeAll("pub const ZIG_GENERATED_TOOL_NAMES: &[&str] = &[\n");
    inline for (generated_tools) |tool| {
        try writer.print("    \"{s}\",\n", .{tool.name});
    }
    try writer.writeAll("];\n\n");

    try writer.writeAll("pub const ZIG_GENERATED_TOOLS: &[GeneratedTool] = &[\n");
    inline for (generated_tools) |tool| {
        try writer.print(
            "    GeneratedTool {{ name: \"{s}\", label: \"{s}\", mutates: {} }},\n",
            .{ tool.name, tool.label, tool.mutates },
        );
    }
    try writer.writeAll("];\n");
}

test "tool registry descriptors are comptime-visible" {
    try std.testing.expectEqual(@as(usize, 4), generated_tools.len);
    comptime {
        if (generated_tools[0].name.len == 0) @compileError("tool names must be non-empty");
    }
}
